server:
  port: 16989

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.hd.source.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: 1
      #logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: hzh081215@qq.com #QQ邮箱
    password: rxkbioiqkvkfbief #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: hzh081215@qq.com #与上面的username保持一致
  freemarker:
    charset: UTF-8
    suffix: .ftl
    content-type: text/html; charset=utf-8
    template-loader-path: classpath:/templates
    cache: false
    settings:
      template_update_delay: 0
  mvc:
    static-path-pattern: /static/**

wx-appid: wx851145b8f1cdf10d
wx-secret: f8278c5f904ddb85ff86a04378109c79

dns:
   http: http://www.24beauties.xyz
   https: https://www.24beauties.xyz
   web-site: https://www.24beauties.xyz/qms