spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 基本属性 url、user、password 193.112.46.15 192.168.246.128 173.82.114.131
      url: jdbc:mysql://106.12.161.232:12306/eshop?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: '!@GoNe2o30yIf3sA82ZU'
      # 配置初始化大小、最小、最大 (通常来说，只需要修改initialSize、minIdle、maxActive)
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis:  60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 106.12.161.232
    port: 10379
    password: '!@*GoNe2o30yIf3sA82ZU'    # 密码（默认为空）
    timeout: 10000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 200  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 3      # 连接池中的最小空闲连接

logging:
  config: classpath:logback-dev.xml

request:
  prefix: ''